packages:
  - apps/*
  - packages/*
  - tools/*
allowBuilds:
  "@napi-rs/canvas": true

catalog:
  "@chenglou/pretext": ^0.0.6
  "@napi-rs/canvas": ^1.0.0
  "@playwright/test": ^1.59.1
  "@tanstack/history": ^1.161.6
  "@tiptap/extension-table": ^3.22.5
  "@tiptap/react": ^3.22.5
  "@types/node": ^24
  nitro: 3.0.260429-beta
  opentype.js: ^1.3.5
  pdfjs-dist: ^5.7.284
  react-reconciler: ^0.33.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.20
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  yoga-layout: ^3.2.1

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
